name: 'sdg_dbt_vault'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sdg_dbt_vault:
    # Capa de Staging: Vistas para limpiar y estandarizar
    staging:
      +materialized: view
      +schema: staging
    
    # Capa de Vault: Tablas persistentes (Hubs, Links, Satélites)
    vault:
      +materialized: table
      +schema: vault
      
    # Capa de Marts: Tablas o vistas según necesidades de consumo
    marts:
      +materialized: table
      +schema: marts